<?php
declare(strict_types=1); header('Content-Type: application/json; charset=utf-8');
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);echo json_encode(['success'=>false,'message'=>'Method not allowed.']);exit;}
$config=require __DIR__.'/../config/config.php'; $body=json_decode(file_get_contents('php://input'),true)??[];
$first=trim((string)($body['first_name']??''));$last=trim((string)($body['last_name']??''));$email=trim((string)($body['email']??''));$phone=trim((string)($body['phone']??''));$country=trim((string)($body['country']??''));$currency=strtoupper(trim((string)($body['currency']??'')));$amount=(float)($body['amount']??0);$message=trim((string)($body['message']??''));
if($first===''||$last===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||$amount<=0||!in_array($currency,$config['app']['currency_whitelist'],true)){http_response_code(422);echo json_encode(['success'=>false,'message'=>'Please provide a valid name, email, currency and donation amount.']);exit;}
if(strlen($message)>500){http_response_code(422);echo json_encode(['success'=>false,'message'=>'Message is too long.']);exit;}
if(str_contains($config['pesapal']['consumer_key'],'YOUR_PESAPAL')||str_contains($config['pesapal']['notification_id'],'YOUR_REGISTERED')){http_response_code(503);echo json_encode(['success'=>false,'message'=>'Payment gateway is not configured. Add PesaPal credentials and the registered IPN ID in config/config.php.']);exit;}
$base=$config['pesapal']['environment']==='live'?'https://pay.pesapal.com/v3':'https://cybqa.pesapal.com/pesapalv3';
function pp(string $url,array $payload=[],?string $token=null):array{$ch=curl_init($url);$h=['Accept: application/json','Content-Type: application/json'];if($token)$h[]='Authorization: Bearer '.$token;curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$payload===[]?'GET':'POST',CURLOPT_POSTFIELDS=>$payload===[]?null:json_encode($payload),CURLOPT_HTTPHEADER=>$h,CURLOPT_TIMEOUT=>30,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2]);$raw=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('Payment provider connection failed: '.$err);$data=json_decode($raw,true);if($code<200||$code>=300)throw new RuntimeException($data['error']['message']??'Payment provider returned an error.');return is_array($data)?$data:[];}
try{$auth=pp($base.'/api/Auth/RequestToken',['consumer_key'=>$config['pesapal']['consumer_key'],'consumer_secret'=>$config['pesapal']['consumer_secret']]);$token=$auth['token']??null;if(!$token)throw new RuntimeException('Could not authenticate with payment provider.');$ref='SIDAI-'.date('YmdHis').'-'.bin2hex(random_bytes(4));
 $order=['id'=>$ref,'currency'=>$currency,'amount'=>round($amount,2),'description'=>'Donation to SIDAI CBO','callback_url'=>$config['pesapal']['callback_url'],'cancellation_url'=>$config['pesapal']['callback_url'].'?cancelled=1','notification_id'=>$config['pesapal']['notification_id'],'billing_address'=>['email_address'=>$email,'phone_number'=>$phone,'country_code'=>strtoupper(substr($country,0,2)?:'KE'),'first_name'=>$first,'middle_name'=>'','last_name'=>$last,'line_1'=>'Donation','line_2'=>'','city'=>'','state'=>'','postal_code'=>'','zip_code'=>'']];
 $result=pp($base.'/api/Transactions/SubmitOrderRequest',$order,$token);if(empty($result['redirect_url']))throw new RuntimeException('No secure checkout URL was returned.');
 $pdo=new PDO('sqlite:'.__DIR__.'/../data/donations.sqlite');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec('CREATE TABLE IF NOT EXISTS donations(id INTEGER PRIMARY KEY AUTOINCREMENT, merchant_reference TEXT UNIQUE, tracking_id TEXT, first_name TEXT,last_name TEXT,email TEXT,phone TEXT,country TEXT,currency TEXT,amount REAL,message TEXT,status TEXT DEFAULT "PENDING",created_at TEXT,updated_at TEXT)');$s=$pdo->prepare('INSERT INTO donations(merchant_reference,tracking_id,first_name,last_name,email,phone,country,currency,amount,message,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$now=date('c');$s->execute([$ref,$result['order_tracking_id']??null,$first,$last,$email,$phone,$country,$currency,round($amount,2),$message,'PENDING',$now,$now]);
 echo json_encode(['success'=>true,'redirect_url'=>$result['redirect_url'],'order_tracking_id'=>$result['order_tracking_id']??null,'reference'=>$ref]);
}catch(Throwable $e){http_response_code(502);echo json_encode(['success'=>false,'message'=>$e->getMessage()]);}
